pub mod ast;
pub mod checker;
pub mod diagnostic;
pub mod ffi;
pub mod formatter;
pub mod lexer;
pub mod loader;
pub mod native;
pub mod parser;
pub mod plot;
pub mod runtime;
pub mod value;
pub const VERSION: &str = env!("CARGO_PKG_VERSION");
